#!/bin/sh

#Start polybar first
bash ~/.config/polybar/launch.sh &

# Set mouse and keyboard speed
bash ~/.config/autostart/startup.sh &

# Var defines
color0=#3B4252
color2=#D8DEE9

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
	true
    else
	sxhkd &
    fi
    sleep 5
done &

# Set keyboard layout and speed
setxkbmap -layout us

# Basic config
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config window_gap      8
bspc config border_width    2
bspc config top_padding     6
bspc config right_padding   6
bspc config left_padding    6
bspc config bottom_padding  6
bspc config top_monocle_padding    0
bspc config left_monocle_padding   0
bspc config right_monocle_padding  0
bspc config bottom_monocle_padding 0
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "$color0"
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config presel_feedback_color "$color2"

# Application rules
bspc rule -a Steam desktop="^4"

# Auto start programs
sleep 0.50
nitrogen --set-auto "$HOME/.config/bg.jpg" &
/usr/games/steam --start &

# Move to Desktop 1
bspc desktop -f 1
